name: 'Composer Dependencies'
description: 'Manages Composer dependencies installation'
inputs:
  php_version:
    description: 'PHP version to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Composer dependencies
      shell: bash
      working-directory: ${{ github.workspace }}/module
      run: |
        if [ ! -f "composer.json" ]; then
          echo "No composer.json found, skipping dependencies installation"
          exit 0
        fi
        
        echo "Installing Composer dependencies with PHP ${{ inputs.php_version }}..."
        
        # Create temporary composer.json without mikopbx/core
        TMP_COMPOSER_FILE=$(mktemp)
        jq 'del(.require["mikopbx/core"])' composer.json > "$TMP_COMPOSER_FILE"
        
        # Ensure correct permissions
        docker run --rm \
          -v ${{ github.workspace }}/module:/app \
          -w /app \
          ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest \
          bash -c '
            # Configure git
            git config --global --add safe.directory /app
            
            # Install dependencies with basic autoloader
            composer install \
              --no-dev \
              --no-plugins \
              --no-scripts \
              --prefer-dist \
              --no-progress \
              --no-interaction \
              --no-autoloader
            
            # Generate simple autoloader
            composer dump-autoload \
              --no-dev
          '
        
        # Clean up
        rm "$TMP_COMPOSER_FILE"

        # Verify autoloader was created
        if [ ! -f "vendor/autoload.php" ]; then
          echo "Error: autoload.php was not generated"
          ls -la vendor/
          exit 1
        fi
