name: 'Manage GitHub Releases'
description: 'Creates and manages GitHub releases for both production and development builds'

inputs:
  version:
    description: 'Release version'
    required: true
  version_tag:
    description: 'Release version tag'
    required: true
  module_filename:
    description: 'Module archive filename'
    required: true
  changelog:
    description: 'Changelog content'
    required: true

runs:
  using: "composite"
  steps:
    - name: Manage GitHub Releases
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_VERSION_TAG: ${{ inputs.version_tag }}
        INPUT_MODULE_FILENAME: ${{ inputs.module_filename }}
        INPUT_CHANGELOG: ${{ inputs.changelog }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        cd module
        
        # Function to create a new release with proper formatting
        create_release() {
          local prerelease=$1
          local tag="$INPUT_VERSION_TAG"
          local title
          local notes="$INPUT_CHANGELOG"
          local extra_args=""
          
          # Format release title based on branch
          if [ "$prerelease" = "true" ]; then
            title="Development Build $INPUT_VERSION"
            extra_args="--prerelease"
            echo "Creating development release: $title"
          else
            title="Release $INPUT_VERSION"
            echo "Creating production release: $title"
          fi
          
          # Create release with appropriate settings
          gh release create "$tag" \
            "$INPUT_MODULE_FILENAME" \
            --title "$title" \
            --notes "$notes" \
            --target $GITHUB_SHA \
            $extra_args
          
          echo "Release created successfully: $title"
        }
        
        # Function to cleanup old development releases
        cleanup_old_releases() {
          echo "Cleaning up old development releases..."
          
          # Check if there are any releases first
          if ! gh release list --limit 1 &>/dev/null; then
            echo "No releases found - skipping cleanup"
            return 0
          fi
          
          # Get list of prerelease tags, sorted by creation date
          OLD_RELEASES=$(gh release list \
            --limit 999 \
            --exclude-drafts \
            | grep "Pre-release" \
            | awk '{print $1}' \
            | tail -n +6 || true)
          
          if [ -n "$OLD_RELEASES" ]; then
            echo "Found old releases to cleanup:"
            echo "$OLD_RELEASES"
            
            # Delete old releases
            for tag in $OLD_RELEASES; do
              echo "Deleting old development release: $tag"
              gh release delete "$tag" --yes || true
              git push --delete origin "$tag" || true
            done
          else
            echo "No old development releases to cleanup"
          fi
        }
        
        # Main release logic based on branch
        if [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
          echo "Processing development release..."
          create_release true
          cleanup_old_releases
          
        elif [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
          echo "Processing production release..."
          create_release false
          
        else
          echo "Skipping release creation for branch: $GITHUB_REF"
        fi
        
        echo "Release management completed successfully"
