name: 'Publish Module'
description: 'Publishes module to files.miko.ru and releases.mikopbx.com'

inputs:
  module_filename:
    description: 'Module archive filename'
    required: true
  version:
    description: 'Module version'
    required: true
  changelog:
    description: 'Changelog content'
    required: true
  php_version:
    description: 'PHP version to use (7.4 or 8.3)'
    required: true
    default: '7.4'  

runs:
  using: "composite"
  steps:
    # Create WebDAV directories
    - name: Create WebDAV directory structure
      shell: bash
      env:
        OWNCLOUD_AUTH: ${{ env.OWNCLOUD_AUTH }}
        WEBDAV_ROOT: ${{ env.WEBDAV_ROOT }}
      run: |
        # Create directory structure on files.miko.ru
        for DIR in "update.miko.ru" "update.miko.ru/MikoPBXPlugins" "update.miko.ru/MikoPBXPlugins/${{ github.event.repository.name }}"; do
          echo "Creating directory: $DIR"
          docker run --rm -v $PWD/module:/app -w /app \
            ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest \
            curl -u "$OWNCLOUD_AUTH" -X MKCOL "$WEBDAV_ROOT/$DIR"
        done
