name: 'Build Docker Image'
description: 'Builds Docker image for MikoPBX module development'

inputs:
  php_version:
    description: 'PHP version to use (7.4 or 8.3)'
    required: true
    default: '7.4'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.action_path }}
        file: ${{ github.action_path }}/Dockerfile.${{ inputs.php_version }}
        push: true
        tags: |
          ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest
        cache-from: |
          type=registry,ref=ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest
        cache-to: type=registry,ref=ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:buildcache,mode=max
