name: 'Build Docker Image'
description: 'Builds Docker image for MikoPBX module development'

inputs:
  php_version:
    description: 'PHP version to use (7.4 or 8.3)'
    required: true
    default: '7.4'

runs:
  using: 'composite'
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Check if image exists
      shell: bash
      id: check_image
      run: |
        # Try to pull the image first
        if docker pull ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest >/dev/null 2>&1; then
          echo "Image exists and was pulled successfully"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Image does not exist or pull failed"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      if: steps.check_image.outputs.exists != 'true'
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      if: steps.check_image.outputs.exists != 'true'
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.action_path }}
        file: ${{ github.action_path }}/Dockerfile.${{ inputs.php_version }}
        push: true
        tags: |
          ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest
        cache-from: |
          type=registry,ref=ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest
        cache-to: type=registry,ref=ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:buildcache,mode=max

    # Verify image is available
    - name: Verify Docker image
      shell: bash
      run: |
        if ! docker image inspect ghcr.io/mikopbx/modules-builder-php${{ inputs.php_version }}:latest >/dev/null 2>&1; then
          echo "Error: Docker image is not available after build/pull"
          exit 1
        fi
