name: 'Build Docker Image'
description: 'Builds Docker image for MikoPBX module development'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.action_path }}
        file: ${{ github.action_path }}/Dockerfile
        push: true  # Включаем push в registry для кэширования
        tags: |
          ghcr.io/mikopbx/modules-builder:latest
          ghcr.io/mikopbx/modules-builder:${{ github.sha }}
        load: true  # Также загружаем образ локально
        cache-from: |
          type=registry,ref=ghcr.io/mikopbx/modules-builder:latest
          type=registry,ref=ghcr.io/mikopbx/modules-builder:buildcache
        cache-to: type=registry,ref=ghcr.io/mikopbx/modules-builder:buildcache,mode=max
