FROM ubuntu:jammy

ENV DEBIAN_FRONTEND noninteractive

# Install basic requirements
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml-xpath-perl \
    software-properties-common \
    gnupg \
    git \
    curl \
    jq \
    zip \
    ca-certificates \
    apt-transport-https \
    build-essential

# Add PHP 8.3 and Phalcon repositories
RUN add-apt-repository ppa:ondrej/php && \
    curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash

# Install PHP 8.3 and all required extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
    php8.3 \
    php8.3-cli \
    php8.3-common \
    php8.3-curl \
    php8.3-zip \
    php8.3-mbstring \
    php8.3-xml \
    php8.3-intl \
    php8.3-mysql \
    php8.3-psr \
    php8.3-dev \
    php8.3-phalcon \
    php8.3-ldap \
    php8.3-mailparse \
    php8.3-opcache \
    php8.3-readline \
    php8.3-soap \
    php8.3-bcmath \
    && rm -rf /var/lib/apt/lists/*

# Verify PHP extensions
RUN php -m

# Install Composer
RUN cd /tmp \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

# Configure PHP
RUN echo "extension=phalcon.so" > /etc/php/8.3/cli/conf.d/30-phalcon.ini

WORKDIR /app
