FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

# Install basic requirements
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml-xpath-perl \
    software-properties-common \
    gnupg \
    git \
    curl \
    jq \
    zip \
    unzip \
    ca-certificates \
    apt-transport-https \
    build-essential

# Add PHP 8.3 and Phalcon repositories
RUN add-apt-repository ppa:ondrej/php && \
    curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash

# Install PHP 8.3 and all required extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
    php8.3 \
    php8.3-cli \
    php8.3-common \
    php8.3-bcmath \
    php8.3-bz2 \
    php8.3-ctype \
    php8.3-curl \
    php8.3-date \
    php8.3-dom \
    php8.3-ev \
    php8.3-event \
    php8.3-fileinfo \
    php8.3-filter \
    php8.3-gettext \
    php8.3-gmp \
    php8.3-hash \
    php8.3-iconv \
    php8.3-igbinary \
    php8.3-json \
    php8.3-ldap \
    php8.3-libxml \
    php8.3-mailparse \
    php8.3-mbstring \
    php8.3-mikopbx \
    php8.3-msgpack \
    php8.3-openssl \
    php8.3-pcntl \
    php8.3-pcre \
    php8.3-pdo \
    php8.3-pdo-sqlite \
    php8.3-phalcon \
    php8.3-phar \
    php8.3-posix \
    php8.3-random \
    php8.3-redis \
    php8.3-reflection \
    php8.3-gd \
    php8.3-shmop \
    php8.3-simplexml \
    php8.3-sockets \
    php8.3-sqlite3 \
    php8.3-tokenizer \
    php8.3-xdebug \
    php8.3-xml \
    php8.3-xmlreader \
    php8.3-xmlwriter \
    php8.3-yaml \
    php8.3-zip \
    && rm -rf /var/lib/apt/lists/*

# Verify PHP extensions
RUN php -m

# Install Composer
RUN cd /tmp \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

# Configure PHP
RUN echo "extension=phalcon.so" > /etc/php/8.3/cli/conf.d/30-phalcon.ini

WORKDIR /app
