name: Extension Publish Workflow

on:
  workflow_call:
    inputs:
      initial_version:
        required: true
        type: string
        description: 'Initial version for the module (e.g., "1.18")'
    secrets:
      OWNCLOUD_AUTH:
        required: true
      MIKO_LIC_REST_VENDOR_ID:
        required: true
      MIKO_LIC_REST_API_KEY:
        required: true
      MIKO_LIC_HOSTNAME:
        required: true
      WEBDAV_ROOT:
        required: true
      SHARE_API_URL:
        required: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: ./.github/actions/checkout
      
      # Validation steps
      - name: Validate module configuration
        id: validate
        uses: ./.github/actions/validate
      
      # Version management
      - name: Manage versions
        id: version
        uses: ./.github/actions/versioning
        with:
          initial_version: ${{ inputs.initial_version }}
      
      # Build environment
      - name: Setup build environment
        uses: ./.github/actions/docker-build
      
      # Dependencies
      - name: Handle dependencies
        uses: ./.github/actions/composer
      
      # Create module archive
      - name: Create module package
        id: archive
        uses: ./.github/actions/archive
        with:
          version: ${{ steps.version.outputs.new_version }}
      
      # Generate changelog if enabled
      - name: Generate changelog
        id: changelog
        if: steps.validate.outputs.changelog_enabled == 'true'
        uses: ./.github/actions/changelog
      
      # Publish to files.miko.ru if enabled
      - name: Publish module
        if: |
          github.ref == 'refs/heads/master' && 
          steps.validate.outputs.publish_release == 'true'
        env:
          OWNCLOUD_AUTH: ${{ secrets.OWNCLOUD_AUTH }}
          WEBDAV_ROOT: ${{ secrets.WEBDAV_ROOT }}
          SHARE_API_URL: ${{ secrets.SHARE_API_URL }}
          MIKO_LIC_REST_VENDOR_ID: ${{ secrets.MIKO_LIC_REST_VENDOR_ID }}
          MIKO_LIC_REST_API_KEY: ${{ secrets.MIKO_LIC_REST_API_KEY }}
          MIKO_LIC_HOSTNAME: ${{ secrets.MIKO_LIC_HOSTNAME }}
        uses: ./.github/actions/publish
        with:
          module_filename: ${{ steps.archive.outputs.filename }}
          version: ${{ steps.version.outputs.new_version }}
          changelog: ${{ steps.changelog.outputs.changelog }}
      
      # Create releases if enabled
      - name: Create releases
        if: steps.validate.outputs.create_github_release == 'true'
        uses: ./.github/actions/release
        with:
          version: ${{ steps.version.outputs.new_version }}
          version_tag: ${{ steps.version.outputs.new_version_tag }}
          module_filename: ${{ steps.archive.outputs.filename }}
          changelog: ${{ steps.changelog.outputs.changelog }}
