# File: .github-workflows/.github/workflows/extension-publish.yml
name: Extension Publish Workflow

on:
  workflow_call:
    inputs:
      initial_version:
        required: true
        type: string
        description: 'Initial version for the module (e.g., "1.18")'
    secrets:
      OWNCLOUD_AUTH:
        required: true
      MIKO_LIC_REST_VENDOR_ID:
        required: true
      MIKO_LIC_REST_API_KEY:
        required: true
      MIKO_LIC_HOSTNAME:
        required: true
      WEBDAV_ROOT:
        required: true
      SHARE_API_URL:
        required: true

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # First checkout both repositories
      - name: Checkout module repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: module

      - name: Checkout workflows repository
        uses: actions/checkout@v4
        with:
          repository: mikopbx/.github-workflows
          path: .github-workflows

      # Now we can use local actions from the workflows repository
      - name: Validate module configuration
        id: validate
        uses: ./.github-workflows/.github/actions/validate
        
      - name: Manage versions
        id: version
        uses: ./.github-workflows/.github/actions/versioning
        with:
          initial_version: ${{ inputs.initial_version }}

      - name: Setup build environment
        uses: ./.github-workflows/.github/actions/docker-build
        with:
          php_version: ${{ steps.validate.outputs.php_version }}

      - name: Handle dependencies
        uses: ./.github-workflows/.github/actions/composer
        with:
          php_version: ${{ steps.validate.outputs.php_version }}

      - name: Create module package
        id: archive
        uses: ./.github-workflows/.github/actions/archive
        with:
          version: ${{ steps.version.outputs.new_version }}

      - name: Generate changelog
        id: changelog
        if: steps.validate.outputs.changelog_enabled == 'true'
        uses: ./.github-workflows/.github/actions/changelog

      - name: Publish module
        if: |
          github.ref == 'refs/heads/master' && 
          steps.validate.outputs.publish_release == 'true'
        env:
          OWNCLOUD_AUTH: ${{ secrets.OWNCLOUD_AUTH }}
          WEBDAV_ROOT: ${{ secrets.WEBDAV_ROOT }}
          SHARE_API_URL: ${{ secrets.SHARE_API_URL }}
          MIKO_LIC_REST_VENDOR_ID: ${{ secrets.MIKO_LIC_REST_VENDOR_ID }}
          MIKO_LIC_REST_API_KEY: ${{ secrets.MIKO_LIC_REST_API_KEY }}
          MIKO_LIC_HOSTNAME: ${{ secrets.MIKO_LIC_HOSTNAME }}
        uses: ./.github-workflows/.github/actions/publish
        with:
          php_version: ${{ steps.validate.outputs.php_version }}
          module_filename: ${{ steps.archive.outputs.filename }}
          version: ${{ steps.version.outputs.new_version }}
          changelog: ${{ steps.changelog.outputs.changelog }}

      - name: Manage GitHub releases
        if: steps.validate.outputs.create_github_release == 'true'
        uses: ./.github-workflows/.github/actions/release
        with:
          version: ${{ steps.version.outputs.new_version }}
          version_tag: ${{ steps.version.outputs.new_version_tag }}
          module_filename: ${{ steps.archive.outputs.filename }}
          changelog: ${{ steps.changelog.outputs.changelog }}
